### ISSUE TITLE
Incluir en el Readme los miembros del equipo

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es4b#2]
En el archivo Readme.md  del repositorio es debe crearse una sección llamada **Miembros del equipo**  en la que cada integrante realice un commit que incluya 2 cosas:

- Nombre completo
- UO

**Comment by UO276213** [comment]
Añadido

**Comment by uo277878** [comment]
Añadido

**Comment by uo271355** [comment]
Añadidos todos los nombres

**Comment by HugoLebredo** [comment]
Muy bien..... Por cierto ¿Quien es "Laís García"?
