### ISSUE TITLE
Arreglando https en el despliegue

### ISSUE THREAD

**Issue by uo277553** [Arquisoft/dede_es4b#247]
Como no tenemos el protocolo https para nuestra aplicación, la integración con SOLID no funciona.

**Comment by UO276213** [comment]
Ya está todo implementado y funciona Solid

**Comment by pglez82** [comment]
Confirmado. Lo he probado y me funciona. Enhorabuena por el trabajo.

**Comment by labra** [comment]
Idem...también lo he probado y funciona...buen trabajo!
